{% set name = "simclr" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google-research/simclr/releases/download/{{ version }}/simclr-{{ version }}.tar.gz
  sha256: fe0fd617f2b539fcd699f9e4fad90d552eea3d4f9b8aa69121cdafc9cbdb4bca

build:
  number: 0
  script: cp -r $SRC_DIR $SP_DIR/simclr

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - simclr

about:
  home: https://github.com/simplejson/simplejson
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE 
  summary: 'A Simple Framework for Contrastive Learning of Visual Representations'
  doc_url: https://github.com/google-research/simclr/tree/1.0
  dev_url: https://github.com/google-research/simclr/tree/1.0

extra:
  recipe-maintainers:
    - JennaLipscomb
