{% set name = "simclr" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google-research/simclr/archive/{{ version }}.tar.gz
  sha256: fe0fd617f2b539fcd699f9e4fad90d552eea3d4f9b8aa69121cdafc9cbdb4bca

build:
  number: 0
  script: cp -r $SRC_DIR $SP_DIR/simclr

requirements:
  host:
    - python  ==3.6
    - pip
  run:
    - python ==3.6
    - tensorflow ==2.0
    - tensorflow-datasets ==1.2.0 
    - tensorflow-hub ==0.8.0

test:
  imports:
    - simclr

about:
  home: https://github.com/google-research/simclr
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE 
  summary: 'A Simple Framework for Contrastive Learning of Visual Representations'
  doc_url: https://github.com/google-research/simclr/tree/1.0
  dev_url: https://github.com/google-research/simclr/tree/1.0

extra:
  recipe-maintainers:
    - JennaLipscomb
